services:
  redis:
    image: redis:7-alpine
    networks:
      - app-network

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
    volumes:
      - ./logs:/worker/logs
    networks:
      - app-network

  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - worker
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
